cargo-features = ["strip"]

[workspace]
members = [
	"client",
	"server",
]

[profile.release]
lto = true
strip = "symbols"
codegen-units = 1

[patch.crates-io]
iced_wgpu = { git = "https://github.com/Imberflur/iced.git" }

